# Generated by Django 4.0.4 on 2022-07-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategorytyName', models.CharField(max_length=200, null=True)),
                ('CategoryImg', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
