# Generated by Django 4.0.4 on 2022-07-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='CategorytyName',
            new_name='CategoryName',
        ),
    ]
