# Generated by Django 4.0.4 on 2022-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='productimg',
            field=models.ImageField(null=True, upload_to='media/ProductImages'),
        ),
    ]
