# Generated by Django 4.0.4 on 2022-07-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_productdb_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='productprice',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
