# Generated by Django 4.0.4 on 2022-07-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_contactusdb_usercartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusdb',
            old_name='massege',
            new_name='messege',
        ),
    ]
