# Generated by Django 4.0.4 on 2022-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_massege_contactusdb_messege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusdb',
            name='messege',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
